import React from 'react';
import { format } from 'date-fns';
import { formatNumber } from '../../utils/formatters';
import { ServiceReceipt } from '../../types/serviceReceipt';
import { ServiceReceiptFilters } from './ServiceReceiptReport';
import { useAuthContext } from '../AuthContext';
import { calculateReceiptTotal } from '../../utils/metrics';

interface PrintableReportProps {
  receipts: ServiceReceipt[];
  filters: ServiceReceiptFilters;
}

export function PrintableReport({ receipts, filters }: PrintableReportProps) {
  const { user } = useAuthContext();
  
  const unpaidReceipts = receipts.filter(receipt => receipt.payment_status !== 'paid');
  const totalAmount = unpaidReceipts.reduce((sum, receipt) => sum + calculateReceiptTotal(receipt), 0);

  return (
    <div className="print:p-0">
      <div className="print:mb-2 print:mt-[0.1cm]">
        <h1 className="text-lg font-bold print:mb-1">Unpaid Service Receipts Report</h1>
        <div className="text-xs text-gray-600 print:space-y-0">
          <p>Report Period: {filters.startDate ? format(new Date(filters.startDate), 'MMMM d, yyyy') : 'All time'} - {filters.endDate ? format(new Date(filters.endDate), 'MMMM d, yyyy') : 'Present'}</p>
          <p>Generated: {format(new Date(), 'MMMM d, yyyy HH:mm')}</p>
          <p>Generated by: {user?.email}</p>
        </div>
      </div>

      <table className="w-full print:mt-2">
        <thead>
          <tr className="border-t border-b border-gray-200">
            <th className="py-1 text-left text-xs">Serial Number</th>
            <th className="py-1 text-left text-xs">Service Provider</th>
            <th className="py-1 text-left text-xs">Warehouse</th>
            <th className="py-1 text-left text-xs">Service Date</th>
            <th className="py-1 text-left text-xs">Status</th>
            <th className="py-1 text-left text-xs">Payment Status</th>
            <th className="py-1 text-right text-xs">Total Cost</th>
          </tr>
        </thead>
        <tbody>
          {unpaidReceipts.map((receipt) => {
            const totalCost = calculateReceiptTotal(receipt);
            return (
              <tr key={receipt.id} className="border-b border-gray-200">
                <td className="py-1 text-xs">{receipt.serial_number}</td>
                <td className="py-1 text-xs">{receipt.service_provider_name}</td>
                <td className="py-1 text-xs">{receipt.warehouse_number}</td>
                <td className="py-1 text-xs">{format(new Date(receipt.service_date), 'MMM d, yyyy')}</td>
                <td className="py-1 text-xs">{receipt.status}</td>
                <td className="py-1 text-xs">{receipt.payment_status}</td>
                <td className="py-1 text-right text-xs">{formatNumber(totalCost)}</td>
              </tr>
            );
          })}
        </tbody>
        <tfoot>
          <tr className="border-t border-b border-gray-200 font-semibold">
            <td colSpan={6} className="py-1 text-xs">Total Amount</td>
            <td className="py-1 text-right text-xs">{formatNumber(totalAmount)}</td>
          </tr>
        </tfoot>
      </table>

      <div className="print:mt-16 grid grid-cols-3 gap-8">
        <div className="text-center">
          <div className="border-t border-gray-300 pt-2">
            <p className="text-xs font-medium">Prepared By</p>
            <p className="text-xs text-gray-600">{user?.email}</p>
            <p className="text-xs text-gray-600">Date: ________________</p>
          </div>
        </div>
        <div className="text-center">
          <div className="border-t border-gray-300 pt-2">
            <p className="text-xs font-medium">Reviewed By</p>
            <p className="text-xs text-gray-600">Name: ________________</p>
            <p className="text-xs text-gray-600">Date: ________________</p>
          </div>
        </div>
        <div className="text-center">
          <div className="border-t border-gray-300 pt-2">
            <p className="text-xs font-medium">Approved By</p>
            <p className="text-xs text-gray-600">Name: ________________</p>
            <p className="text-xs text-gray-600">Date: ________________</p>
          </div>
        </div>
      </div>
    </div>
  );
}